CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);
CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);
CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);
CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);
CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);
CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);
CREATE INDEX base_contractevent_proposal_id_2f5d508d ON public.base_contractevent USING btree (proposal_id);
CREATE INDEX base_contractevent_round_id_a267b328 ON public.base_contractevent USING btree (round_id);
CREATE INDEX base_contractevent_tx_hash_898fc255_like ON public.base_contractevent USING btree (tx_hash varchar_pattern_ops);
CREATE INDEX base_donation_donor_id_bf07c0a4 ON public.base_donation USING btree (donor_id);
CREATE INDEX base_donation_proposal_id_b5dd5a82 ON public.base_donation USING btree (proposal_id);
CREATE INDEX base_donation_tx_hash_389143bf_like ON public.base_donation USING btree (tx_hash varchar_pattern_ops);
CREATE INDEX base_donor_username_d18354e2_like ON public.base_donor USING btree (username varchar_pattern_ops);
CREATE INDEX base_donor_wallet_id_21388e0d ON public.base_donor USING btree (wallet_id);
CREATE INDEX base_governancetoken_wallet_id_c94cc7ae ON public.base_governancetoken USING btree (wallet_id);
CREATE INDEX base_match_proposal_id_d6a627fc ON public.base_match USING btree (proposal_id);
CREATE INDEX base_match_round_id_a28a1dd7 ON public.base_match USING btree (round_id);
CREATE INDEX base_payout_proposal_id_6d90cffb ON public.base_payout USING btree (proposal_id);
CREATE INDEX base_payout_round_id_059e5fa2 ON public.base_payout USING btree (round_id);
CREATE INDEX base_payout_tx_hash_af782574_like ON public.base_payout USING btree (tx_hash varchar_pattern_ops);
CREATE INDEX base_proposal_proposer_id_0e730da4 ON public.base_proposal USING btree (proposer_id);
CREATE INDEX base_proposal_round_id_1676cedb ON public.base_proposal USING btree (round_id);
CREATE INDEX base_qfresult_proposal_id_ead65b11 ON public.base_qfresult USING btree (proposal_id);
CREATE INDEX base_qfresult_round_id_455441c4 ON public.base_qfresult USING btree (round_id);
CREATE INDEX base_round_matching_pool_id_d09b4fd5 ON public.base_round USING btree (matching_pool_id);
CREATE INDEX base_sybilscore_wallet_id_ac28f92f ON public.base_sybilscore USING btree (wallet_id);
CREATE INDEX base_wallet_address_1645f022_like ON public.base_wallet USING btree (address varchar_pattern_ops);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);
